name: CI
on: 
  push:
    branches:
     - "develop"
  pull_request:
    branches:
     - "develop"

# Run linter with github actions for quick feedbacks.
# Run macos tests with github actions. Linux (CPU & GPU) tests currently runs on CircleCI
jobs:
  continue-on-error: true
  linter:
    runs-on: ubuntu-latest
    # run on PRs, or commits to facebookresearch (not internal)
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8==3.8.1 flake8-bugbear flake8-comprehensions isort==4.3.21
          python -m pip install black==21.4b2
          flake8 --version
      - name: isort
        run: |
          echo "Running isort"
          isort -c -sp .
      - name: black
        run: |
          echo "Running black"
          black -l 100 --check .
      - name: flake8
        run: |
          echo "Running flake8"
          flake8 .
